const words = [
    "apple",
    "banana",
    "javascript",
    "socket",
    "dynamic",
    "keyboard",
    "multiplayer",
    "battle",
    "react",
    "server",
    "express",
    "synchronization",
    "typing",
    "engine",
    "victory",
    "arrive", "attend", "average", "balance", "brave", "celebrate", "chance", "choice",
  "compare", "complete", "confident", "connect", "create", "culture", "decide", "describe",
  "despite", "develop", "different", "difficult", "discover", "effect", "effort", "energy",
  "enjoy", "enough", "event", "experience", "explain", "extra", "famous", "feature",
  "festival", "forward", "habit", "happen", "health", "heavy", "honest", "hope",
  "identify", "imagine", "important", "include", "increase", "individual", "interest",
  "involve", "knowledge", "laugh", "apple", "beach", "brain", "bread", "break", "brown", "carry", "chair", "cloud", "dance",
  "dream", "drink", "early", "earth", "eight", "enjoy", "every", "field", "fight", "first",
  "floor", "focus", "fruit", "glass", "grape", "great", "group", "happy", "heart", "heavy",
  "horse", "house", "juice", "knife", "laugh", "light", "match", "money", "music", "night",
  "noise", "peace", "phone", "place", "plant", "point", "queen", "quick", "river", "smile",
  "ability", "balance", "believe", "between", "brother", "capture", "country", "decide", "display", "evening",
  "example", "feature", "festival", "freedom", "general", "happen", "healthy", "history", "holiday", "husband",
  "imagine", "important", "journey", "library", "message", "morning", "natural", "patient", "picture", "popular",
  "protect", "quiet", "reading", "respect", "science", "service", "silence", "special", "student", "subject",
  "support", "teacher", "through", "trouble", "variety", "village", "visitor", "weather", "welcome", "without"
  ];
  
  module.exports = words;